### ISSUE TITLE
テストでエラーが出る

### ISSUE THREAD

**Issue by yosuke-yasuda** [double-y/django#2]
python2.7.9で

``` sh
$ ./tests/runtest.py
```

をするとエラーが発生

**Comment by yosuke-yasuda** [comment]
```

Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
........................................................................................................................................EEEEEEEEEEEEEEEE.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEsssssssssEEEEEEEEEEEEEEEEEEEEEE.E.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE..EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE..E...EE.EEEEEEEEEEEEEEEEEEEEEEEEEEEE.EEEEEEEEEEEEEE.........EEEEEEEEE..E...E.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.....EEEEEE.EEEEEEEEEEEEEEEEEEEEEEEEEE.EEs.ssssssssss.EEEEEEE.EEEEEEEEEEEEEEEEEE.EsEE.EE..EEEssE.EEEEEEEEEEEEEEE.EEEEs............EE......E......................................EE......E...................................ssssssssssssssssssssssssssssssssssssssssssssssss........EEEEEEE.EEEEE.E.......EE.......EEInternal Server Error: /debug/
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yasudayousuke/oss_hack/django_dev/django/tests/context_processors/views.py", line 12, in debug_processor
    return render(request, 'context_processors/debug.html', context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/loader.py", line 92, in render_to_string
    return template.render(context, request)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 198, in render
    return self._render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 957, in render
    bit = node.render_annotated(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 924, in render_annotated
    return self.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 957, in render
    bit = node.render_annotated(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 924, in render_annotated
    return self.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/backends/base/base.py", line 428, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by yosuke-yasuda** [comment]
```
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yasudayousuke/oss_hack/django_dev/django/tests/context_processors/views.py", line 12, in debug_processor
    return render(request, 'context_processors/debug.html', context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/loader.py", line 92, in render_to_string
    return template.render(context, request)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 198, in render
    return self._render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 957, in render
    bit = node.render_annotated(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 924, in render_annotated
    return self.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 957, in render
    bit = node.render_annotated(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/base.py", line 924, in render_annotated
    return self.render(context)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/query.py", line 1068, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/Users/yasudayousuke/oss_hack/django_dev/django_dev_py2/lib/python2.7/site-packages/Django-1.9.dev20150710070019-py2.7.egg/django/db/backends/base/base.py", line 428, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by yosuke-yasuda** [comment]
3.4.3でもエラーが出た

**Comment by yosuke-yasuda** [comment]
`$ % export LC_ALL=ja_JP.UTF-8`と`$ export LANG=ja_JP.UTF-8`を設定すると解決

**Comment by yosuke-yasuda** [comment]
``` sh
$ ./runtests.py           
Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_parent/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
..................................................................................................................................................................................................................................................................................[1]    9705 segmentation fault  ./runtests.py
```

どこでsegmentation faultが出てるのか調べる

**Comment by yosuke-yasuda** [comment]
fail発見

```
./test_runner
+ /Users/yasudayousuke/oss_hack/django_dev/djangodev/bin/python ./runtests.py ./test_runner
Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_parent/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
.....F...........ss.......................
======================================================================
FAIL: test_duplicates_ignored (test_runner.test_discover_runner.DiscoverRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_parent/tests/test_runner/test_discover_runner.py", line 127, in test_duplicates_ignored
    self.assertEqual(single, dups)
AssertionError: 251 != 252
```
